"use strict";
/* tslint:disable */
/* eslint-disable */
// this is an auto generated file. This will be overwritten
Object.defineProperty(exports, "__esModule", { value: true });
exports.deleteProduct = exports.updateProduct = exports.createProduct = exports.deleteCategory = exports.updateCategory = exports.createCategory = void 0;
exports.createCategory = "\n  mutation CreateCategory(\n    $input: CreateCategoryInput!\n    $condition: ModelCategoryConditionInput\n  ) {\n    createCategory(input: $input, condition: $condition) {\n      id\n      name\n      products {\n        items {\n          id\n          name\n          description\n          price\n          imageUrl\n          categoryId\n          createdAt\n          updatedAt\n          __typename\n        }\n        nextToken\n        __typename\n      }\n      createdAt\n      updatedAt\n      __typename\n    }\n  }\n";
exports.updateCategory = "\n  mutation UpdateCategory(\n    $input: UpdateCategoryInput!\n    $condition: ModelCategoryConditionInput\n  ) {\n    updateCategory(input: $input, condition: $condition) {\n      id\n      name\n      products {\n        items {\n          id\n          name\n          description\n          price\n          imageUrl\n          categoryId\n          createdAt\n          updatedAt\n          __typename\n        }\n        nextToken\n        __typename\n      }\n      createdAt\n      updatedAt\n      __typename\n    }\n  }\n";
exports.deleteCategory = "\n  mutation DeleteCategory(\n    $input: DeleteCategoryInput!\n    $condition: ModelCategoryConditionInput\n  ) {\n    deleteCategory(input: $input, condition: $condition) {\n      id\n      name\n      products {\n        items {\n          id\n          name\n          description\n          price\n          imageUrl\n          categoryId\n          createdAt\n          updatedAt\n          __typename\n        }\n        nextToken\n        __typename\n      }\n      createdAt\n      updatedAt\n      __typename\n    }\n  }\n";
exports.createProduct = "\n  mutation CreateProduct(\n    $input: CreateProductInput!\n    $condition: ModelProductConditionInput\n  ) {\n    createProduct(input: $input, condition: $condition) {\n      id\n      name\n      description\n      price\n      imageUrl\n      categoryId\n      category {\n        id\n        name\n        products {\n          nextToken\n          __typename\n        }\n        createdAt\n        updatedAt\n        __typename\n      }\n      createdAt\n      updatedAt\n      __typename\n    }\n  }\n";
exports.updateProduct = "\n  mutation UpdateProduct(\n    $input: UpdateProductInput!\n    $condition: ModelProductConditionInput\n  ) {\n    updateProduct(input: $input, condition: $condition) {\n      id\n      name\n      description\n      price\n      imageUrl\n      categoryId\n      category {\n        id\n        name\n        products {\n          nextToken\n          __typename\n        }\n        createdAt\n        updatedAt\n        __typename\n      }\n      createdAt\n      updatedAt\n      __typename\n    }\n  }\n";
exports.deleteProduct = "\n  mutation DeleteProduct(\n    $input: DeleteProductInput!\n    $condition: ModelProductConditionInput\n  ) {\n    deleteProduct(input: $input, condition: $condition) {\n      id\n      name\n      description\n      price\n      imageUrl\n      categoryId\n      category {\n        id\n        name\n        products {\n          nextToken\n          __typename\n        }\n        createdAt\n        updatedAt\n        __typename\n      }\n      createdAt\n      updatedAt\n      __typename\n    }\n  }\n";
